import jsPDF from "jspdf";
import type { PackingItem } from "../types";
import { format } from "date-fns";

interface ExportPackingListOptions {
  tripName: string;
  destination: string;
  startDate: string;
  endDate: string;
  packingList: PackingItem[];
}

/**
 * Export packing list to PDF
 * @param options - Trip and packing list information
 */
export const exportPackingListToPDF = ({
  tripName,
  destination,
  startDate,
  endDate,
  packingList,
}: ExportPackingListOptions) => {
  // Create PDF document (A4 size)
  const doc = new jsPDF();

  // Page dimensions
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = 20;

  // === HEADER ===
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("📦 PACKING LIST", pageWidth / 2, yPosition, { align: "center" });

  yPosition += 10;
  doc.setDrawColor(66, 135, 245);
  doc.setLineWidth(0.5);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);

  // Trip Information
  yPosition += 10;
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Trip: ${tripName}`, margin, yPosition);

  yPosition += 7;
  doc.text(`Destination: ${destination}`, margin, yPosition);

  yPosition += 7;
  const formattedStart = format(new Date(startDate), "MMM dd, yyyy");
  const formattedEnd = format(new Date(endDate), "MMM dd, yyyy");
  doc.text(`Dates: ${formattedStart} - ${formattedEnd}`, margin, yPosition);

  yPosition += 5;
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  // Group items by category
  const CATEGORIES = [
    "Clothing",
    "Toiletries",
    "Health & Wellness",
    "Electronics",
    "Documents",
    "Other",
  ];

  const itemsByCategory: Record<string, PackingItem[]> = {};
  CATEGORIES.forEach((cat) => {
    itemsByCategory[cat] = packingList.filter((item) => item.category === cat);
  });

  // Handle unknown categories
  const knownCategories = new Set(CATEGORIES);
  const otherItems = packingList.filter(
    (item) => !knownCategories.has(item.category)
  );
  if (otherItems.length > 0) {
    itemsByCategory["Other"] = [
      ...(itemsByCategory["Other"] || []),
      ...otherItems,
    ];
  }

  // === PACKING ITEMS ===
  CATEGORIES.forEach((category) => {
    const items = itemsByCategory[category] || [];
    if (items.length === 0) return;

    // Check if we need a new page
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    // Category Header
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(66, 135, 245);
    doc.text(category.toUpperCase(), margin, yPosition);
    yPosition += 8;

    // Category Items
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);

    items.forEach((item) => {
      // Check if we need a new page
      if (yPosition > 270) {
        doc.addPage();
        yPosition = 20;
      }

      // Checkbox
      const checkboxX = margin + 5;
      const checkboxY = yPosition - 3;
      const checkboxSize = 4;

      // Draw checkbox square
      doc.setDrawColor(100, 100, 100);
      doc.setLineWidth(0.3);
      doc.rect(checkboxX, checkboxY, checkboxSize, checkboxSize);

      // If checked, add checkmark
      if (item.checked) {
        doc.setDrawColor(66, 135, 245);
        doc.setLineWidth(0.8);
        doc.line(
          checkboxX + 0.5,
          checkboxY + 2,
          checkboxX + 1.5,
          checkboxY + 3.5
        );
        doc.line(
          checkboxX + 1.5,
          checkboxY + 3.5,
          checkboxX + 3.5,
          checkboxY + 0.5
        );
      }

      // Item text
      const itemText = item.name;
      const textX = checkboxX + checkboxSize + 3;

      if (item.checked) {
        doc.setTextColor(150, 150, 150);
        // Add strikethrough for checked items
        const textWidth = doc.getTextWidth(itemText);
        doc.setDrawColor(150, 150, 150);
        doc.setLineWidth(0.2);
        doc.line(textX, yPosition - 1, textX + textWidth, yPosition - 1);
      } else {
        doc.setTextColor(0, 0, 0);
      }

      doc.text(itemText, textX, yPosition);
      yPosition += 7;
    });

    yPosition += 3; // Space between categories
  });

  // === FOOTER ===
  const footerY = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(9);
  doc.setTextColor(128, 128, 128);
  doc.setFont("helvetica", "italic");
  doc.text("Generated by Wanderlust Planner", pageWidth / 2, footerY, {
    align: "center",
  });

  const generatedDate = format(new Date(), "MMM dd, yyyy HH:mm");
  doc.text(generatedDate, pageWidth / 2, footerY + 4, { align: "center" });

  // === SAVE PDF ===
  const fileName = `${tripName.replace(/[^a-z0-9]/gi, "_")}-Packing-List.pdf`;
  doc.save(fileName);
};
